### ISSUE TITLE
Please invite me to the GitHub Community Organization

### ISSUE THREAD

**Issue by shivhere007** [Magic-Academy/.github#650]
### Name

Shivam Prasad Singh

### Discord Username (if applicable)

shiv007_70175

### Additional Context

Joining this open source community is an exciting opportunity to give back and grow as a developer. I’d love to contribute my skills, collaborate with others, and learn new approaches to problem-solving. By being a part of this community, I can make meaningful contributions that benefit others while improving my own skills and gaining insights from experienced developers. It's inspiring to be in a space where ideas are shared openly, and everyone has a role in building something valuable for all.

**Comment by songdaochuanshu** [comment]
<h1>It's great having you contribute to this project</h1> Welcome to the community :nerd_face:<p>If you would like to continue contributing to open source and would like to do it with an awesome inclusive community, you should join our <a href="https://discord.gg/G2jgHeQfy4">Discord Server</a> and our <a href="https://github.com/Magic-Academy">GitHub Organisation</a> - we help and encourage each other to contribute to open source little and often 🤓 . Any questions let us know.</p>

**Comment by shivhere007** [comment]
I have joined the discord server.

**Comment by songdaochuanshu** [comment]
> I have joined the discord server but not got the invitation yet. @songdaochuanshu

  Dear Shivam Prasad Singh,

  Thank you very much for your interest in joining the Magic-Academy community! We sincerely apologize for the delay in processing your request due to recent system updates.

  Your invitation to join the GitHub Organization has now been sent. Welcome to the community 🎉

  Please remember to accept the invitation and make it public so it appears on your GitHub profile for everyone else to see. You can do this by finding your name in the GitHub organization list and changing the dropdown to public:
  https://github.com/orgs/Magic-Academy/people

  Once again, we apologize for any inconvenience caused and appreciate your patience. If you have any questions or need further assistance, feel free to reach out.

  Best regards,
  The Magic-Academy Team
